version: '3.8'


services:
  JobForge.api:
    image: jobforge
    container_name: jobforge.api
    build:
      context: .
      dockerfile: jobforge/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5001
    depends_on:
      - jobforge.database


  jobforge.database:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: jobforge.database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Velvet2006
      - POSTGRES_DB=jobforge
    volumes:
      - ./.containers/postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

